# Generated by Django 3.2.3 on 2021-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210516_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userfc',
            name='technology',
            field=models.ManyToManyField(related_name='users', to='profiles.Technology'),
        ),
    ]
